include: package:flutter_lints/flutter.yaml

linter:
  rules:
    constant_identifier_names: false
    non_constant_identifier_names: false
    use_build_context_synchronously: false

    unnecessary_statements: true
    prefer_relative_imports: true
    directives_ordering: true

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
  errors:
    invalid_annotation_target: ignore