name: news_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  hooks_riverpod: 2.5.1
  flutter_hooks: 0.20.5
  dio: 5.5.0+1
  cached_network_image: 3.3.1
  webview_flutter: 4.8.0
  connectivity_plus: 6.0.3
  envied: 0.5.4+1
  freezed: 2.5.2
  freezed_annotation: 2.4.4
  json_annotation: 4.9.0
  equatable: 2.0.5
  hive: 2.2.3
  hive_flutter: 1.1.0
  intl: 0.19.0
  flutter_cache_manager: 3.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  build_runner: 2.4.9
  json_serializable: 6.8.0
  envied_generator: 0.5.4+1
  flutter_lints: 4.0.0
  mocktail: 1.0.4


flutter:
  uses-material-design: true